/**
 * tools/write-errors.mjs — turning a sandbox refusal into something a DM can act on.
 *
 * ## The defect this exists to fix (T7)
 *
 * When a write was refused, the DM saw exactly this:
 *
 *     Error: cannot write "D:\\DND\\campaigns\\<campaign>\\characters\\alice.state.json":
 *     file access denied under workspace-write mode
 *
 * It restates the MODE and says nothing else. It does not say which root the
 * write was judged against, why this path is outside it, or what to do about it.
 * The original bug report's words: the message should "name the POLICY and the
 * REMEDY, not merely restate the sandbox mode."
 *
 * ## Why this is a WRAPPER and not a fix to the message
 *
 * That sentence is generated by the HOST PLATFORM (`dsh-fs-sandbox`), not by
 * this bundle. The bundle cannot change it — and must not try: the platform
 * lives in `node_modules` and an upgrade would silently revert any edit, which
 * is exactly the kind of change that looks fixed and is not.
 *
 * So the bundle CATCHES the refusal at its own call sites and rewrites it into
 * an actionable message, keeping the original error as `cause` so nothing is
 * swallowed.
 *
 * ## What can honestly be said
 *
 * Three of the four useful things are knowable, and the fourth is knowable by
 * WHO the caller is:
 *
 *   1. WHICH PATH was refused — read it off the original message.
 *   2. WHICH ROOT it was judged against — this is the resolved policy the write
 *      was attempted WITH. When the bundle supplied a session policy, that root
 *      is the session's cwd; when it did not, it is the platform's process-cwd
 *      fallback. Both are reportable, and the distinction is the whole diagnosis.
 *   3. WHAT TO DO — depends on whether a session policy was supplied at all,
 *      which is precisely the T2/T6 finding.
 *
 * ## The most important thing this module says
 *
 * If the write carried NO session policy AND the refusal happened, the message
 * says so in as many words. That combination is the original fatal defect
 * reproducing itself, and it is not the same failure as "the campaign really is
 * outside your workspace". Conflating the two is what made this bug take a
 * whole task board to find.
 */

/** The platform's refusal code, as it appears in `Error.code` and in messages. */
export const SANDBOX_DENIED = 'FS_SANDBOX_DENIED'

/**
 * Does this error look like a sandbox refusal?
 *
 * Checks the structured `code` first, then falls back to the message text,
 * because the platform does not guarantee the code survives every wrapping
 * layer (the observed live failure carried it only in the message).
 *
 * @param error - anything thrown.
 * @returns true when this is a filesystem sandbox refusal.
 */
export function isSandboxDenial(error) {
  if (error === undefined || error === null) return false
  if (error.code === SANDBOX_DENIED) return true
  const message = String(error.message ?? error)
  return message.includes(SANDBOX_DENIED) || message.includes('file access denied under')
}

/**
 * Extract the refused path from a platform refusal message.
 *
 * The platform's wording is `cannot write "<path>": file access denied ...`.
 * Returns null when the message does not carry one, rather than inventing a
 * path — a wrong path in a diagnostic is worse than an absent one.
 *
 * @param error - the refusal.
 * @returns the quoted path, or null.
 */
export function refusedPathOf(error) {
  const message = String(error?.message ?? error ?? '')
  const match = /cannot (?:write|read|create|delete) "([^"]+)"/i.exec(message)
  return match === null ? null : match[1]
}

/**
 * Describe a refusal in actionable terms.
 *
 * @param error - the refusal that was caught.
 * @param options - `{ policy, operation, campaign }`.
 *   `policy` is the resolved `SandboxExecutionPolicy` the write was attempted
 *   with, or undefined when none was available. It is the single most
 *   diagnostic fact available here.
 * @returns a multi-line message: what happened, against which root, and what to do.
 */
export function describeWriteRefusal(error, options = {}) {
  const { policy, operation = 'write', campaign } = options
  const path = refusedPathOf(error)

  const lines = []
  lines.push('dsh-dnd: the sandbox refused this ' + operation + '.')

  if (path !== null) lines.push('  path  : ' + path)
  else lines.push('  path  : (the platform message did not name one)')

  if (policy !== undefined && policy !== null) {
    // A session policy WAS supplied, so the root below is the session's own
    // workspace. A refusal against THIS root means the campaign genuinely sits
    // outside the session's workspace — a real policy answer, not a bundle bug.
    lines.push('  root  : ' + String(policy.workspaceRoot) + '  (this session\'s workspace)')
    lines.push('  mode  : ' + String(policy.mode))
    if (policy.sessionId !== undefined && policy.sessionId !== null) {
      lines.push('  session: ' + String(policy.sessionId))
    }
    lines.push('')
    lines.push('  This write was judged against the SESSION workspace, which is the')
    lines.push('  correct boundary. The path above is therefore genuinely outside it.')
    lines.push('  Remedies:')
    lines.push('    - start the session with its cwd at (or above) the campaign root;')
    lines.push('    - or move the campaign under the session workspace.')
  } else {
    // NO session policy. This is the original defect's signature: the write was
    // judged against the harness process's cwd instead of the session's.
    lines.push('  root  : unknown — the platform fell back to the harness PROCESS cwd')
    lines.push('  mode  : not resolved for this session')
    lines.push('')
    lines.push('  DIAGNOSIS: this write carried NO session policy. The path was judged')
    lines.push('  against the harness process\'s own working directory, not this')
    lines.push('  session\'s workspace. That is the known defect behind every dnd_*')
    lines.push('  write failing while reads and dice kept working.')
    lines.push('  Remedies:')
    lines.push('    - the tool must be called by an agent, so its session can be resolved;')
    lines.push('    - check that the host exposes `sessions` and `sandboxPolicy`;')
    lines.push('    - this is NOT a statement that the campaign is outside your workspace.')
  }

  if (campaign !== undefined && campaign !== null) {
    lines.push('')
    lines.push('  campaign: ' + String(campaign))
  }

  return lines.join('\n')
}

/**
 * Run a write, translating a sandbox refusal into an actionable error.
 *
 * The original error is preserved as `cause`, so a caller (or a human reading a
 * stack trace) can still see the platform's own words.
 *
 * @param fn - a thunk performing the write.
 * @param options - `{ policy, operation, campaign }`, as `describeWriteRefusal`.
 * @returns whatever `fn` returns.
 * @throws the ORIGINAL error, untouched, when it is not a sandbox refusal —
 *   this must never disguise an unrelated failure as a policy problem.
 */
export async function withWriteDiagnosis(fn, options = {}) {
  try {
    return await fn()
  } catch (error) {
    if (!isSandboxDenial(error)) throw error
    throw new Error(describeWriteRefusal(error, options), { cause: error })
  }
}
